services:
  frontend:
    # No Swarm, a imagem deve ser pré-construída
    image: alexignacio/zapmonei-frontend:latest
    networks:
      - automacoes
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.zapmonei.rule=Host(`zapmonei.com.br`)"
        - "traefik.http.routers.zapmonei.entrypoints=websecure"
        - "traefik.http.routers.zapmonei.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.zapmonei.loadbalancer.server.port=3000"

networks:
  automacoes:
    external: true
